"""change user column name

Revision ID: 415aecff6983
Revises: 
Create Date: 2022-02-17 16:52:30.237023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "415aecff6983"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table("user") as batch_op:
    #     batch_op.alter_column(

    #     )
    #     pass
    op.alter_column("user", "email", new_column_name="username")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "username", new_column_name="email")
    # ### end Alembic commands ###
